"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, CircleDollarSign, AlertCircle, RefreshCw, X } from "lucide-react";
import type { Game, GameSession } from "@/types/game";
import { useStartSession, useEndSession } from "@/hooks/useGames";

interface SpinWheelGameProps {
  game: Game;
  onClose: () => void;
  onSuccess: () => void;
}

interface Slice {
  id: string;
  label: string;
  campaignSlug: string | null;
  weight: number;
  color: string;
}

const DEFAULT_SLICES: Slice[] = [
  { id: "s1", label: "10 Coins", campaignSlug: "spin-wheel-10", weight: 30, color: "#E53935" },
  { id: "s2", label: "Free Drink", campaignSlug: "spin-wheel-drink", weight: 10, color: "#1E88E5" },
  { id: "s3", label: "Try Again", campaignSlug: null, weight: 25, color: "#757575" },
  { id: "s4", label: "50 Coins", campaignSlug: "spin-wheel-50", weight: 15, color: "#43A047" },
  { id: "s5", label: "Chili Dessert", campaignSlug: "spin-wheel-dessert", weight: 15, color: "#FB8C00" },
  { id: "s6", label: "Jackpot!", campaignSlug: "spin-wheel-jackpot", weight: 5, color: "#D4A31C" },
];

export function SpinWheelGame({ game, onClose, onSuccess }: SpinWheelGameProps) {
  const startSessionMutation = useStartSession();
  const endSessionMutation = useEndSession();

  const [slices, setSlices] = useState<Slice[]>(DEFAULT_SLICES);
  const [isSpinning, setIsSpinning] = useState(false);
  const [wheelRotation, setWheelRotation] = useState(0);
  const [activeSession, setActiveSession] = useState<GameSession | null>(null);
  const [spinResult, setSpinResult] = useState<any>(null);
  const [showResultModal, setShowResultModal] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Parse slices from game configuration
  useEffect(() => {
    const config = game.rewardConfig as any;
    if (config?.slices && Array.isArray(config.slices) && config.slices.length > 0) {
      // Assign premium colors to custom slices
      const colors = ["#E53935", "#1E88E5", "#43A047", "#FB8C00", "#8E24AA", "#D4A31C", "#00ACC1", "#FDD835"];
      const formattedSlices = config.slices.map((slice: any, index: number) => ({
        id: slice.id || `s${index}`,
        label: slice.label || "Prize",
        campaignSlug: slice.campaignSlug || null,
        weight: slice.weight || 10,
        color: slice.color || colors[index % colors.length],
      }));
      setSlices(formattedSlices);
    }
  }, [game]);

  const handleSpinClick = async () => {
    if (isSpinning) return;
    setErrorMessage(null);
    setSpinResult(null);

    try {
      // 1. Call startSession API
      const session = await startSessionMutation.mutateAsync({
        gameSlug: game.slug,
        clientData: {},
      });
      setActiveSession(session);

      const rolledSliceId = session.metadata?.outcomeSliceId;
      if (!rolledSliceId) {
        throw new Error("No outcome generated by server");
      }

      // 2. Find matching slice index
      const sliceIndex = slices.findIndex((s) => s.id === rolledSliceId);
      if (sliceIndex === -1) {
        throw new Error("Invalid outcome slice ID returned by server");
      }

      // 3. Calculate target rotation
      const numSlices = slices.length;
      const segmentAngle = 360 / numSlices;
      
      // Target angle: Align selected slice center with top pointer (0 / 360 deg)
      // Since pointer is at top (0 deg), slice index 0 should center at 0 deg, index 1 at 360 - segmentAngle, etc.
      const targetAngle = 360 - (sliceIndex * segmentAngle) - (segmentAngle / 2);
      
      // Add 5-6 full spins for animation impact
      const extraSpins = 5 * 360;
      const finalRotation = extraSpins + targetAngle;

      setIsSpinning(true);
      setWheelRotation(finalRotation);

      // 4. Wait for spin animation to complete (4s duration)
      setTimeout(async () => {
        try {
          // 5. Call endSession API to claim reward and finalize session
          const outcome = await endSessionMutation.mutateAsync({
            sessionId: session.id,
            clientData: { sliceId: rolledSliceId },
          });

          setSpinResult(outcome);
          setShowResultModal(true);
          onSuccess();
        } catch (err: any) {
          const msg = err.response?.data?.message || err.message || "Failed to claim spin reward";
          setErrorMessage(msg);
        } finally {
          setIsSpinning(false);
        }
      }, 4100);

    } catch (err: any) {
      const msg = err.response?.data?.message || err.message || "Failed to start spin session";
      setErrorMessage(msg);
      setIsSpinning(false);
    }
  };

  const segmentAngle = 360 / slices.length;

  return (
    <div className="relative w-full max-w-md bg-white rounded-3xl p-6 border border-stone-200 shadow-xl flex flex-col items-center select-none overflow-hidden">
      
      {/* Top Banner */}
      <div className="w-full flex items-center justify-between mb-4 border-b border-stone-100 pb-3">
        <div className="flex items-center gap-2">
          <Sparkles className="size-5 text-brand-red animate-pulse" />
          <h3 className="font-heading text-lg font-bold text-on-surface uppercase tracking-wide">
            {game.name}
          </h3>
        </div>
        <button
          onClick={onClose}
          disabled={isSpinning}
          className="p-1 rounded-full hover:bg-stone-100 text-stone-400 hover:text-stone-700 transition cursor-pointer"
        >
          <X className="size-5" />
        </button>
      </div>

      {errorMessage && (
        <div className="w-full bg-red-50 text-red-700 border border-red-200/50 rounded-xl p-3 flex items-start gap-2 text-xs mb-4">
          <AlertCircle className="size-4 shrink-0 mt-0.5" />
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Wheel Wrapper */}
      <div className="relative w-72 h-72 sm:w-80 sm:h-80 my-4 flex items-center justify-center">
        
        {/* Outer Wheel Decorative Ring */}
        <div className="absolute inset-0 rounded-full border-8 border-brand-green/90 shadow-lg bg-stone-900 pointer-events-none" />

        {/* Wheel LED Lights */}
        {Array.from({ length: 12 }).map((_, i) => (
          <div
            key={i}
            className={`absolute w-2 h-2 rounded-full z-10 transition-colors duration-300 ${isSpinning && i % 2 === 0 ? "bg-amber-300 shadow-[0_0_8px_#fcd34d]" : "bg-white opacity-80"}`}
            style={{
              transform: `rotate(${i * 30}deg) translateY(-144px)`,
            }}
          />
        ))}

        {/* Pointer Indicator */}
        <div className="absolute top-[-10px] left-1/2 -translate-x-1/2 z-20 pointer-events-none">
          <div className="w-6 h-8 bg-brand-red rounded-t-full shadow-md transform rotate-180" style={{ clipPath: "polygon(50% 0%, 0% 100%, 100% 100%)" }} />
        </div>

        {/* The SVG Rotating Wheel */}
        <div
          className="w-full h-full rounded-full overflow-hidden transition-transform transform-gpu"
          style={{
            transform: `rotate(${wheelRotation}deg)`,
            transition: isSpinning ? "transform 4s cubic-bezier(0.15, 0.85, 0.25, 1)" : "none",
          }}
        >
          <svg viewBox="0 0 200 200" className="w-full h-full">
            {slices.map((slice, i) => {
              const startAngle = i * segmentAngle - 90; // Align with SVG coordinates
              const endAngle = (i + 1) * segmentAngle - 90;
              const radStart = (startAngle * Math.PI) / 180;
              const radEnd = (endAngle * Math.PI) / 180;

              const x1 = 100 + 100 * Math.cos(radStart);
              const y1 = 100 + 100 * Math.sin(radStart);
              const x2 = 100 + 100 * Math.cos(radEnd);
              const y2 = 100 + 100 * Math.sin(radEnd);

              const largeArcFlag = segmentAngle > 180 ? 1 : 0;
              const pathData = `M 100 100 L ${x1} ${y1} A 100 100 0 ${largeArcFlag} 1 ${x2} ${y2} Z`;

              // Text Rotation
              const textAngle = startAngle + segmentAngle / 2;
              const radText = (textAngle * Math.PI) / 180;
              const tx = 100 + 65 * Math.cos(radText);
              const ty = 100 + 65 * Math.sin(radText);

              return (
                <g key={slice.id}>
                  {/* Slice path */}
                  <path d={pathData} fill={slice.color} stroke="#fff" strokeWidth="0.5" />
                  
                  {/* Label */}
                  <text
                    x={tx}
                    y={ty}
                    fill="#fff"
                    fontSize="7"
                    fontWeight="bold"
                    fontFamily="sans-serif"
                    textAnchor="middle"
                    alignmentBaseline="middle"
                    transform={`rotate(${textAngle + 90}, ${tx}, ${ty})`}
                  >
                    {slice.label}
                  </text>
                </g>
              );
            })}
            
            {/* Center Circle */}
            <circle cx="100" cy="100" r="18" fill="#fff" stroke="#D4A31C" strokeWidth="3" />
          </svg>
        </div>

        {/* Center Spin Action Button */}
        <button
          onClick={handleSpinClick}
          disabled={isSpinning}
          className="absolute z-30 size-14 rounded-full bg-amber-500 hover:bg-amber-600 disabled:bg-stone-300 text-white font-sans font-extrabold text-xs uppercase tracking-wider flex items-center justify-center shadow-md border-2 border-white hover:scale-105 active:scale-95 disabled:scale-100 transition-all cursor-pointer"
        >
          {isSpinning ? (
            <RefreshCw className="size-5 animate-spin" />
          ) : (
            "SPIN"
          )}
        </button>
      </div>

      <div className="mt-2 text-center">
        <p className="text-xs font-sans text-stone-500 leading-normal">
          {game.description}
        </p>
      </div>

      {/* Result Modal Overlay */}
      <AnimatePresence>
        {showResultModal && spinResult && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-stone-900/90 z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className="bg-white rounded-3xl p-6 max-w-sm w-full text-center border border-stone-200 shadow-2xl flex flex-col items-center gap-4"
            >
              <div className="size-16 rounded-full bg-amber-100 flex items-center justify-center text-amber-600">
                {spinResult.rewardDecision?.rewardGranted ? (
                  <CircleDollarSign className="size-10 animate-bounce" />
                ) : (
                  <Sparkles className="size-10" />
                )}
              </div>

              <div>
                <h4 className="font-heading text-xl font-extrabold uppercase tracking-tight text-on-surface">
                  {spinResult.rewardDecision?.rewardGranted ? "CONGRATULATIONS!" : "GOOD TRY!"}
                </h4>
                <p className="text-sm font-sans text-stone-500 mt-1">
                  {spinResult.rewardDecision?.reason}
                </p>
              </div>

              {spinResult.rewardDecision?.rewardGranted && spinResult.rewardDecision?.totalCoins > 0 && (
                <div className="bg-amber-500/10 border border-amber-500/20 rounded-2xl px-6 py-3 my-1">
                  <span className="block text-[32px] font-sans font-extrabold text-amber-600 leading-none">
                    +{spinResult.rewardDecision.totalCoins}
                  </span>
                  <span className="text-[10px] font-sans font-bold uppercase tracking-wider text-amber-600/80 block mt-1">
                    Coins Credited
                  </span>
                </div>
              )}

              <button
                onClick={() => {
                  setShowResultModal(false);
                  onClose();
                }}
                className="w-full bg-brand-green hover:bg-brand-green-hover text-white font-sans font-semibold py-3 px-6 rounded-full transition shadow-soft cursor-pointer uppercase text-sm tracking-wider"
              >
                Awesome!
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
