export const DASHBOARD_REWARDS_PERMISSIONS = {
  PROFILE_CREATE: 'DASHBOARD_REWARD_PROFILE_CREATE',
  PROFILE_UPDATE: 'DASHBOARD_REWARD_PROFILE_UPDATE',
  PROFILE_DELETE: 'DASHBOARD_REWARD_PROFILE_DELETE',
  PROFILE_PUBLISH: 'DASHBOARD_REWARD_PROFILE_PUBLISH',
  RULE_CREATE: 'DASHBOARD_REWARD_RULE_CREATE',
  RULE_UPDATE: 'DASHBOARD_REWARD_RULE_UPDATE',
  RULE_DELETE: 'DASHBOARD_REWARD_RULE_DELETE',
  ASSIGNMENT_CREATE: 'DASHBOARD_REWARD_ASSIGNMENT_CREATE',
  ASSIGNMENT_UPDATE: 'DASHBOARD_REWARD_ASSIGNMENT_UPDATE',
  ASSIGNMENT_DELETE: 'DASHBOARD_REWARD_ASSIGNMENT_DELETE',
  OVERRIDE_CREATE: 'DASHBOARD_REWARD_OVERRIDE_CREATE',
  OVERRIDE_UPDATE: 'DASHBOARD_REWARD_OVERRIDE_UPDATE',
  OVERRIDE_DELETE: 'DASHBOARD_REWARD_OVERRIDE_DELETE',
  BULK_OPERATIONS: 'DASHBOARD_REWARD_BULK',
} as const;

export const DASHBOARD_REWARDS_CACHE = {
  PREFIX: 'dashboard:rewards',
  TTL: {
    PROFILES: 120,
    RULES: 120,
    ASSIGNMENTS: 120,
    OVERRIDES: 120,
    PREVIEW: 120,
    ANALYTICS: 300,
    SEARCH: 60,
  },
} as const;

export const DASHBOARD_REWARDS_ERRORS = {
  PROFILE_NOT_FOUND: 'Reward profile not found',
  RULE_NOT_FOUND: 'Reward rule not found',
  ASSIGNMENT_NOT_FOUND: 'Reward assignment not found',
  OVERRIDE_NOT_FOUND: 'Reward override not found',
  STORE_NOT_FOUND: 'Store not found',
  VERSION_NOT_FOUND: 'Version not found',
  CANNOT_ROLLBACK: 'Cannot rollback to this version',
  NOT_PUBLISHED: 'Profile is not published',
  ALREADY_PUBLISHED: 'Profile is already published',
} as const;

export const DASHBOARD_REWARDS_EVENTS = {
  PROFILE_PUBLISHED: 'dashboard-rewards.profile.published',
  RULE_PUBLISHED: 'dashboard-rewards.rule.published',
  ASSIGNMENT_CHANGED: 'dashboard-rewards.assignment.changed',
  OVERRIDE_CHANGED: 'dashboard-rewards.override.changed',
  DEFAULT_PROFILE_CHANGED: 'dashboard-rewards.default-profile.changed',
} as const;
