import { Offer } from "@/types/offers";

export const MOCK_OFFERS: Offer[] = [
  {
    offerId: "off-wf-1",
    outletId: "out-whitefield",
    title: "ITPL Corporate Feast Combo",
    subtitle: "2 Biryanis + Tandoori Starter + Mocktails",
    description: "Exclusive lunch & dinner combo crafted for ITPL foodies. Get 2 Mutton or Chicken Biryanis with Paneer Skewers & 2 Mint Coolers.",
    discount: "30% OFF",
    validity: "Valid till end of month",
    couponCode: "ITPLFEAST",
    minimumOrder: "Min. Order ₹599",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop",
    badge: "BESTSELLER",
    category: "combos",
    terms: ["Applicable on dine-in & takeaway at Whitefield outlet", "Cannot be combined with coins redemption"],
    priority: 1,
    active: true,
  },
  {
    offerId: "off-wf-2",
    outletId: "out-whitefield",
    title: "Buy 1 Get 1 Tandoori Starter",
    subtitle: "Applicable on Paneer & Chicken Starters",
    description: "Order any signature Tandoori starter and get a second starter of equal or lesser value absolutely free.",
    discount: "BUY 1 GET 1",
    validity: "Valid on Weekdays",
    couponCode: "BOGOSTARTER",
    minimumOrder: "Min. Order ₹399",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800&auto=format&fit=crop",
    badge: "WEEKDAY DEAL",
    category: "dine-in",
    terms: ["Dine-in only at GreenChillyz Whitefield", "Offer valid from Mon-Thu 12PM-6PM"],
    priority: 2,
    active: true,
  },
  {
    offerId: "off-wf-3",
    outletId: "out-whitefield",
    title: "Flat ₹150 Off Home Delivery",
    subtitle: "Direct online delivery through GreenChillyz App",
    description: "Get ₹150 instant discount on your first online direct delivery order from Whitefield kitchen.",
    discount: "FLAT ₹150 OFF",
    validity: "Limited period offer",
    couponCode: "FREEDEL150",
    minimumOrder: "Min. Order ₹499",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop",
    badge: "DELIVERY SPECIAL",
    category: "delivery",
    terms: ["Valid only on online delivery orders", "Limited to one redemption per customer"],
    priority: 3,
    active: true,
  },
  {
    offerId: "off-ind-1",
    outletId: "out-indiranagar",
    title: "100 Feet Nightlife Platter & Drinks",
    subtitle: "Signature Kebabs + Craft Mocktails",
    description: "Enjoy our chef's special tandoori kebab platter paired with two free signature craft mocktails.",
    discount: "25% OFF",
    validity: "Valid everyday after 7 PM",
    couponCode: "NIGHTLIFE25",
    minimumOrder: "Min. Order ₹699",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop",
    badge: "EVENING DEAL",
    category: "dine-in",
    terms: ["Valid only at Indiranagar outlet", "Subject to table availability"],
    priority: 1,
    active: true,
  },
  {
    offerId: "off-ind-2",
    outletId: "out-indiranagar",
    title: "Double GreenChillyz Coins Reward",
    subtitle: "Earn 2x Coins on every Indiranagar order",
    description: "Earn double loyalty coins on all dine-in and takeaway orders at Indiranagar for redemption on future meals.",
    discount: "2X COINS",
    validity: "Valid all month",
    couponCode: "IND2XCOINS",
    minimumOrder: "No Min. Order",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800&auto=format&fit=crop",
    badge: "REWARDS BONUS",
    category: "rewards",
    terms: ["Requires registered phone number at billing", "Coins credited within 24 hours"],
    priority: 2,
    active: true,
  },
  {
    offerId: "off-kor-1",
    outletId: "out-koramangala",
    title: "Student & Youth Biryani Combo",
    subtitle: "Handi Biryani + Gulab Jamun + Beverage",
    description: "Show your college ID or use coupon code to get a complete Biryani meal box with dessert and drink.",
    discount: "FLAT ₹120 OFF",
    validity: "Valid all week",
    couponCode: "KORASTUDENT",
    minimumOrder: "Min. Order ₹299",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop",
    badge: "POPULAR",
    category: "combos",
    terms: ["Valid at YellowChillyz Koramangala", "Applicable on dine-in & takeaway"],
    priority: 1,
    active: true,
  },
  {
    offerId: "off-ub-1",
    outletId: "out-ubcity",
    title: "Golden Royal Tasting Menu",
    subtitle: "5-Course Luxury Culinary Experience",
    description: "Experience 5 courses of royal Odisha gastronomy with complimentary welcome aperitifs and chef special dessert.",
    discount: "GOLDEN VIP",
    validity: "Prior Booking Recommended",
    couponCode: "UBGOLDVIP",
    minimumOrder: "Min. 2 Persons",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop",
    badge: "LUXURY VIP",
    category: "dine-in",
    terms: ["Exclusive to GoldenChillyz UB City", "Requires prior table reservation"],
    priority: 1,
    active: true,
  },
  {
    offerId: "off-jay-1",
    outletId: "out-jayanagar",
    title: "Family Weekend Thali Feast",
    subtitle: "Unlimited Royal Thali Refills",
    description: "Bring your family for our special weekend Royal Thali. Get 20% off on tables of 4 or more.",
    discount: "20% OFF",
    validity: "Sat & Sun Only",
    couponCode: "JAYFAMILY",
    minimumOrder: "Min. 4 Persons",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=800&auto=format&fit=crop",
    badge: "FAMILY SPECIAL",
    category: "combos",
    terms: ["Valid on weekends at YellowChillyz Jayanagar", "Dine-in only"],
    priority: 1,
    active: true,
  },
  {
    offerId: "off-hsr-1",
    outletId: "out-hsr-1",
    title: "HSR Express Lunch Box",
    subtitle: "Starter + Main Curry + Naan + Rice",
    description: "Quick 15-minute executive lunch box tailored for HSR startup professionals and remote workers.",
    discount: "FLAT ₹100 OFF",
    validity: "Mon-Fri 12 PM - 3 PM",
    couponCode: "HSREXPRESS",
    minimumOrder: "Min. Order ₹349",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop",
    badge: "EXPRESS LUNCH",
    category: "delivery",
    terms: ["Valid at GreenChillyz HSR Layout", "Applicable on delivery & takeaway"],
    priority: 1,
    active: true,
  },
];
